export type GlossaryEntry = {
  id: string;
  term: string;
  definition: string;
  aliases?: string[];
  category: "billing" | "tariff" | "payment" | "regulation" | "infrastructure" | "subsidy" | "tax";
  countries?: string[];
  seeAlso?: string[];
};

export const UTILITY_GLOSSARY: GlossaryEntry[] = [
  {
    id: "reference-number",
    term: "Reference number",
    definition: "A unique identifier printed at the top of every utility bill, used to look up the bill online. The same number works across all digital channels: utility portal, wallet app, bank app, and SMS short code.",
    aliases: ["consumer number", "account number", "CA number", "premise number", "customer ID", "connection number", "BP number"],
    category: "billing",
  },
  {
    id: "tariff-slab",
    term: "Tariff slab",
    definition: "A consumption band in a graduated (telescopic) electricity tariff. Each slab has a per-unit rate. Units consumed within each band are billed at that band's rate — crossing into a higher slab does not retroactively raise the rate on lower-band units.",
    aliases: ["consumption slab", "billing slab", "tariff band", "rate slab", "unit slab"],
    category: "tariff",
    seeAlso: ["telescopic-tariff", "per-unit-rate"],
  },
  {
    id: "telescopic-tariff",
    term: "Telescopic tariff",
    definition: "A tariff design where each additional consumption slab is priced at a higher per-unit rate, but only the units in that slab are billed at that rate. The total bill is the sum of each slab's charge. Used in Pakistan, India, and most South Asian electricity markets.",
    aliases: ["graduated tariff", "stepped tariff", "progressive tariff", "block tariff"],
    category: "tariff",
    countries: ["pakistan", "india", "bangladesh", "sri-lanka", "nepal"],
    seeAlso: ["tariff-slab"],
  },
  {
    id: "fixed-charge",
    term: "Fixed charge",
    definition: "A flat monthly amount on a utility bill that does not vary with consumption. Also called meter rent, capacity charge, or standing charge. Payable even if the meter recorded zero consumption in the billing cycle.",
    aliases: ["standing charge", "meter rent", "capacity charge", "service charge", "minimum charge", "demand charge"],
    category: "billing",
  },
  {
    id: "fpa",
    term: "Fuel Price Adjustment (FPA)",
    definition: "A monthly variable surcharge on Pakistan electricity bills that passes through changes in fuel input costs (natural gas, furnace oil, coal). Notified by NEPRA by the 15th of each month. Can be positive (consumer pays more) or negative (credit). A major source of bill volatility.",
    aliases: ["FPA", "fuel adjustment charge", "FAC", "fuel surcharge", "fuel cost adjustment"],
    category: "tariff",
    countries: ["pakistan"],
    seeAlso: ["nepra", "pitc"],
  },
  {
    id: "quarterly-tariff-adjustment",
    term: "Quarterly Tariff Adjustment (QTA)",
    definition: "A periodic adjustment NEPRA approves to reconcile actual generation costs against the approved tariff for the prior quarter. Similar to FPA but applied quarterly rather than monthly. Can be positive or negative.",
    aliases: ["QTA", "QTR adjustment", "quarterly adjustment"],
    category: "tariff",
    countries: ["pakistan"],
    seeAlso: ["fpa", "nepra"],
  },
  {
    id: "pitc",
    term: "PITC",
    definition: "Power Information Technology Company — a government entity in Pakistan that operates bill.pitc.com.pk, the shared online bill-check portal for all 13 Pakistan DISCOs. Check Bills Online's live bill fetch for Pakistan runs through PITC.",
    aliases: ["Power Information Technology Company", "PITC portal", "bill.pitc.com.pk"],
    category: "infrastructure",
    countries: ["pakistan"],
    seeAlso: ["disco", "nepra"],
  },
  {
    id: "disco",
    term: "DISCO",
    definition: "Distribution Company — one of Pakistan's 13 electricity distribution utilities: MEPCO (Multan), LESCO (Lahore), IESCO (Islamabad), FESCO (Faisalabad), GEPCO (Gujranwala), PESCO (Peshawar), HESCO (Hyderabad), SEPCO (Sukkur), QESCO (Quetta), TESCO (Tribal), HAZECO (Hazara), and K-Electric (Karachi).",
    aliases: ["distribution company", "electricity distribution utility", "DISCOS", "electricity DISCO"],
    category: "infrastructure",
    countries: ["pakistan"],
    seeAlso: ["pitc", "nepra"],
  },
  {
    id: "nepra",
    term: "NEPRA",
    definition: "National Electric Power Regulatory Authority — Pakistan's electricity sector regulator. Sets tariff for all DISCOs, licenses generation and distribution, and adjudicates consumer complaints. Website: nepra.org.pk.",
    aliases: ["National Electric Power Regulatory Authority", "NEPRA Pakistan"],
    category: "regulation",
    countries: ["pakistan"],
    seeAlso: ["pitc", "disco", "fpa"],
  },
  {
    id: "ogra",
    term: "OGRA",
    definition: "Oil and Gas Regulatory Authority — Pakistan's gas sector regulator. Sets gas tariff for SNGPL and SSGC. Website: ogra.org.pk.",
    aliases: ["Oil and Gas Regulatory Authority", "OGRA Pakistan"],
    category: "regulation",
    countries: ["pakistan"],
  },
  {
    id: "bbps",
    term: "BBPS",
    definition: "Bharat Bill Payment System — the NPCI-operated payment rail used for utility bill payments in India. Enables real-time bill fetch and payment for Adani Electricity, Tata Power, BSES Rajdhani, and hundreds of other Indian utilities through any BBPS-connected bank or app.",
    aliases: ["Bharat Bill Payment System", "NPCI bill payment", "BBPS India"],
    category: "payment",
    countries: ["india"],
    seeAlso: ["cerc"],
  },
  {
    id: "cerc",
    term: "CERC",
    definition: "Central Electricity Regulatory Commission — India's central electricity tariff regulator. Sets inter-state tariffs and oversees state regulators. Website: cercind.gov.in.",
    aliases: ["Central Electricity Regulatory Commission", "CERC India"],
    category: "regulation",
    countries: ["india"],
    seeAlso: ["bbps"],
  },
  {
    id: "late-payment-surcharge",
    term: "Late payment surcharge (LPS)",
    definition: "A penalty applied when a utility bill is paid after the due date. In Pakistan, typically 10% of the energy portion. After the disconnection deadline (usually 30 days past the due date), supply is cut and a reconnection fee is added on top.",
    aliases: ["LPS", "late fee", "surcharge", "penalty", "late charge"],
    category: "billing",
    seeAlso: ["reconnection-fee", "due-date"],
  },
  {
    id: "due-date",
    term: "Due date",
    definition: "The date by which a utility bill must be paid to avoid a late payment surcharge. Typically 14–21 days after the bill date for monthly billing cycles. Printed explicitly on every bill as both an 'amount within due date' and an 'amount after due date' figure.",
    aliases: ["payment due date", "bill due date", "last date", "final date"],
    category: "billing",
    seeAlso: ["late-payment-surcharge"],
  },
  {
    id: "reconnection-fee",
    term: "Reconnection fee",
    definition: "A charge levied to restore electricity, gas, or water supply after disconnection for non-payment. The full outstanding balance plus the reconnection fee must be settled before supply is restored.",
    aliases: ["restoration fee", "reconnection charge", "re-energisation fee"],
    category: "billing",
    seeAlso: ["late-payment-surcharge"],
  },
  {
    id: "css",
    term: "Cross Subsidy Program (CSS)",
    definition: "A Government of Pakistan program at css.pitc.com.pk that registers domestic electricity consumers using ≤200 units/month for the protected (lifeline) tariff. Registration is free, requires CNIC and OTP verification, and savings typically range from Rs 1,500–3,000 per bill for a 150-unit household.",
    aliases: ["CSS", "lifeline tariff registration", "protected tariff", "cross subsidy", "Ehsaas tariff"],
    category: "subsidy",
    countries: ["pakistan"],
    seeAlso: ["lifeline-tariff", "pitc", "nepra"],
  },
  {
    id: "lifeline-tariff",
    term: "Lifeline tariff",
    definition: "A subsidised electricity tariff for low-consumption domestic consumers. Also called 'protected tariff' in Pakistan (A-1a category). Applies automatically or via registration to households consuming below a defined threshold (200 units/month in Pakistan, 100 units/month in Bangladesh, varies by jurisdiction).",
    aliases: ["protected tariff", "lifeline rate", "social tariff", "basic tariff", "A-1a tariff"],
    category: "subsidy",
    seeAlso: ["css", "tariff-slab"],
  },
  {
    id: "dewa",
    term: "DEWA",
    definition: "Dubai Electricity and Water Authority — the government utility providing electricity and water in Dubai, UAE. Bill reference is a 10-digit Premise account number. Website: dewa.gov.ae.",
    aliases: ["Dubai Electricity and Water Authority", "DEWA Dubai"],
    category: "infrastructure",
    countries: ["uae"],
  },
  {
    id: "withholding-tax",
    term: "Withholding tax (electricity, Pakistan)",
    definition: "In Pakistan, a withholding tax is levied on electricity bills: 7.5% for income tax return filers and 15% for non-filers. This amount is adjustable against the consumer's annual income tax liability — filers recover it as a tax credit.",
    aliases: ["WHT", "WH tax", "FBR withholding", "7.5% electricity tax", "income tax on electricity", "tax filer discount"],
    category: "tax",
    countries: ["pakistan"],
  },
  {
    id: "per-unit-rate",
    term: "Per-unit rate",
    definition: "The price charged per unit of utility consumption. For electricity: per kWh (kilowatt-hour). For gas: per cubic metre (m³) or per MMBTU (million British thermal units). For water: per cubic metre or per 1,000 litres.",
    aliases: ["unit rate", "per kWh rate", "energy rate", "consumption rate"],
    category: "tariff",
  },
  {
    id: "sanctioned-load",
    term: "Sanctioned load",
    definition: "The kilowatt capacity approved for a connection, representing the maximum simultaneous demand the service line and meter are designed for. Exceeding this limit results in a load-violation surcharge on the bill.",
    aliases: ["sanctioned capacity", "approved load", "contracted load", "connection capacity"],
    category: "infrastructure",
    countries: ["pakistan", "india"],
  },
  {
    id: "net-metering",
    term: "Net metering",
    definition: "A billing arrangement for solar panel owners where electricity exported to the grid is credited at the prevailing tariff rate against the consumer's consumption charges. The net consumption (import minus export) is billed. Available in Pakistan (AEDB licensed, minimum 1 kW), India, and UAE.",
    aliases: ["solar net metering", "export tariff", "grid export credit", "bidirectional metering", "solar billing"],
    category: "billing",
    seeAlso: ["per-unit-rate"],
  },
  {
    id: "gst-electricity",
    term: "GST on electricity",
    definition: "General Sales Tax applied to electricity bills. In Pakistan: 18% on the total electricity charges. In India: GST rate varies by state (typically 5–18% depending on consumption category). This is a federal/central government tax collected by utilities and remitted to the tax authority.",
    aliases: ["GST", "sales tax electricity", "VAT electricity", "tax on electricity bill"],
    category: "tax",
    seeAlso: ["withholding-tax"],
  },
  {
    id: "meter-reading",
    term: "Meter reading",
    definition: "The numerical value recorded from a utility meter at the end of a billing cycle. Consumption = current reading minus previous reading. If a meter reader cannot access the meter, an estimated reading (marked 'E' on the bill) is used and corrected in the next cycle.",
    aliases: ["meter read", "dial reading", "energy reading", "kWh reading", "estimated reading"],
    category: "billing",
  },
  {
    id: "tariff-category",
    term: "Tariff category",
    definition: "The classification assigned to a connection that determines which rate schedule applies. Common categories: residential (A-1 in Pakistan), commercial (A-2), industrial (B), agricultural (D), bulk supply. Wrong categorisation is a common cause of overbilling — it can be corrected at the utility's customer service office.",
    aliases: ["consumer category", "tariff code", "rate category", "connection type"],
    category: "tariff",
    seeAlso: ["tariff-slab", "lifeline-tariff"],
  },
  {
    id: "circular-debt",
    term: "Circular debt (Pakistan)",
    definition: "The accumulated unpaid obligations in Pakistan's power sector, where DISCOs owe generators, generators owe fuel suppliers, and the chain cannot clear without government intervention. Partially recovered through the Financing Cost Surcharge on every electricity bill.",
    aliases: ["circular debt", "FC surcharge", "financing cost surcharge"],
    category: "regulation",
    countries: ["pakistan"],
  },
];
