import type { ProviderContent } from "@/lib/content/types";

/**
 * MEPCO â€” Multan Electric Power Company. Pakistan template content set.
 *
 * Mirrors the depth of `india/adani-electricity.ts` and follows the same
 * SEO/cluster strategy used by checkbills.pk. Tariff numbers cite the
 * NEPRA tariff schedule and FPA notifications; dates are visible to
 * readers via `lastReviewed`.
 */

export const MEPCO: ProviderContent = {
  hub: {
    metaTitle: "MEPCO Bill Check â€” View, Download & Pay MEPCO Bill Online (Multan)",
    metaDescription:
      "Check MEPCO bill online with your 14-digit reference number. Real-time fetch from PITC, full tariff slabs, JazzCash and Easypaisa payment methods, complaint escalation to NEPRA, and step-by-step guides.",
    intro:
      "Multan Electric Power Company (MEPCO) is the largest distribution company in Pakistan by service area and the second-largest by customer count. Headquartered in Multan, MEPCO supplies electricity to 7.6 million consumers across 13 districts of southern Punjab â€” from Bahawalpur in the south-east to Dera Ghazi Khan in the west and Sahiwal in the north. The company is one of 11 DISCOs that bill consumers through the Power Information Technology Company (PITC) on the unified portal bill.pitc.com.pk, which means the bill-check experience you get on this page works identically whether you live in Multan city or in a village in Rajanpur. This page is the home for everything a MEPCO customer needs to do online: looking up the latest bill, decoding the line items, paying through any approved channel, raising a complaint, applying for a new connection, and understanding when the protected (lifeline) tariff applies to your meter.",
    sections: [
      {
        id: "how-to-check",
        imageQuery: "electricity bill statement",
        heading: "How to check your MEPCO bill online â€” seven working methods",
        paragraphs: [
          "The fastest path is the form at the top of this page: enter the 14-digit reference number printed at the top-right of any recent MEPCO bill, and we fetch the bill in real time from bill.pitc.com.pk on our server. The HTML response from PITC is rendered inside a sandboxed iframe so you see exactly the same bill the post office delivers. The reference number is the only identifier needed â€” there is no login, no captcha, and no fee.",
          "Method 1 â€” checkbillsonline.com (this page). Type the reference, click Check Bill, and the latest cycle's bill loads in 2-5 seconds. You can save the page as a PDF using your browser's print dialog (Ctrl/Cmd+P â†’ Save as PDF). The PDF is identical in layout to the printed bill and is accepted by all Pakistani banks, NADRA, and visa-application centres as a proof of address.",
          "Method 2 â€” bill.pitc.com.pk/mepcobill directly. The same PITC portal that we proxy. The advantage: PITC's portal includes ASP.NET viewstate stamps that mark the bill as a verified original, useful when you need a digitally-signed copy for legal purposes. The disadvantage: PITC's portal is occasionally slow during bill-cycle peaks (the 5th-10th and 25th-28th of each month) and the form layout has not been updated since 2018.",
          "Method 3 â€” MEPCO mobile app. MEPCO publishes an official Android app under the publisher name \"MEPCO Multan Electric Power Company\" on Google Play. The app is the only channel where you can opt in to bill notifications by SMS (free) and PDF email (free). After a one-time OTP login with the mobile number registered to the connection, the app shows the current bill, the last six bills as a graph, and outage notices for your feeder. There is no official iOS app yet; iPhone users should bookmark this page or the PITC portal.",
          "Method 4 â€” SMS to 8118. Send the text \"MEPCO <reference-number>\" (no spaces in the reference) to 8118. You receive a return SMS within 30 seconds with the bill amount, due date, and arrears. The cost is standard SMS (Rs 1-2 depending on operator). This is the only channel that works on a feature phone without an internet connection.",
          "Method 5 â€” JazzCash, Easypaisa, NayaPay, and SadaPay apps. All four wallets accept MEPCO bill fetches under their respective \"Pay Bills\" â†’ \"Electricity\" â†’ \"MEPCO\" tile. Enter the reference, the bill loads in 3-5 seconds, and you can pay in the same screen. Wallet fees range from zero (UPI-style instant fund use) to Rs 25 (card-funded). The wallets are the fastest path from bill view to payment.",
          "Method 6 â€” bank apps. Every major Pakistani bank â€” HBL, UBL, MCB, Allied, Faysal, Bank Alfalah, Meezan, Bank Al Habib, Bank Islami, Standard Chartered, Soneri, Askari, Summit, Silk, JS â€” has MEPCO bill fetching inside its mobile app. The flow is identical: Pay Bills â†’ Electricity â†’ MEPCO â†’ enter reference. Bank channels carry no service charge and the payment settles instantly via 1Link.",
          "Method 7 â€” physical counters. MEPCO accepts cash and pay-order payments at any of its 320+ subdivision and customer-service centres across southern Punjab, as well as at NBP, ABL, HBL, UBL, MCB branches authorised for utility-bill collection. Counter staff will print a duplicate bill for any reference on the spot â€” useful if your printed bill is damaged or lost. Carry your CNIC for the counter clerk to attach to the receipt.",
          "Three further notes about the reference number itself. The MEPCO reference is 14 digits and is the same number that appears in every channel â€” there is no separate \"customer ID\" or \"account number\" for online lookups. The reference encodes your subdivision, feeder, and consumer index, but you do not need to decode it; PITC's database does that automatically. If your reference is on a damaged section of the bill and you cannot read all 14 digits, the easiest recovery is to visit your nearest MEPCO subdivision with your CNIC; they will print a fresh duplicate within five minutes.",
        ],
      },
      {
        id: "understanding-bill",
        imageQuery: "electric grid transformer",
        heading: "Anatomy of a MEPCO bill â€” every line item explained",
        paragraphs: [
          "A typical MEPCO bill carries about 16 line items, more than most international utilities because Pakistan's bill stacks regulatory levies, federal taxes, and adjustment surcharges on top of the per-unit energy charge. Reading them in order matters because some items are calculated on top of others â€” a 10% increase in the energy charge moves the GST, the financial cost surcharge, and several taxes upward by similar percentages even though those line rates have not changed.",
          "Reference Number â€” the 14-digit identifier you use for every online lookup. It is unique to your meter, not to you the person; if you sell the property and the connection transfers, the reference travels with the property.",
          "Consumer Name and Connection Date â€” the registered owner of the meter (often a previous occupant) and the date the connection was first energised. If the name is wrong, see the \"name change\" section on the new-connection spoke.",
          "Tariff Code â€” the most important field on the bill. Codes starting with A-1 are residential; A-1a is the protected (lifeline) slab, A-1b is the unprotected slab. A-2 is commercial, B is industrial, D is agricultural. Cross-check this against your actual use: if a residential property is on A-2 because the previous occupant ran a shop, you are overpaying every month.",
          "Sanctioned Load â€” the kilowatt capacity your meter and service line are designed for. Commonly 1-5 kW for residential. Exceeding sanctioned load draws a load-violation surcharge.",
          "Units Consumed â€” the difference between this cycle's reading and last cycle's reading. The two readings appear in the boxes labelled \"Previous Reading\" and \"Current Reading\". If the units consumed look way off, photograph your meter immediately and compare the reading on it to the \"Current Reading\" printed on the bill; meter-reader errors are not uncommon and can be corrected with a phone call to 118.",
          "Variable Charge (Energy Charge) â€” the biggest cost on most bills. This is the per-unit price multiplied by units consumed. NEPRA notifies the schedule for each tariff slab; residential bills use a slab system where the first 100 units, 101-200 units, 201-300 units, 301-700 units, and above-700 units each have a per-unit rate, climbing steeply. Protected (A-1a) consumers stay on the two lowest slabs.",
          "Fixed Charges â€” a flat monthly amount tied to your sanctioned load. Residential under 5 kW typically pays around Rs 200-400 fixed each month regardless of consumption. Protected consumers are often exempt.",
          "FPA (Fuel Price Adjustment) â€” a monthly pass-through that compensates for changes in the fuel mix cost between when NEPRA set the tariff and when the bill is issued. FPA can be positive (you pay extra) or negative (a refund). NEPRA notifies the FPA on the 15th of each month; the figure on your bill is the FPA for the month before the consumption month, not the current month. FPA can vary from Rs 1 to Rs 7 per unit and is the single most volatile line on Pakistani electricity bills.",
          "QTR Adjustment â€” a quarterly adjustment NEPRA approves to reconcile the previous quarter's actual generation cost against the tariff. Like FPA but lumpier; some quarters QTR is positive, others negative.",
          "GST 17% (or 18% in some districts) â€” the federal General Sales Tax. The base is the total electricity charge before income tax and other levies.",
          "TV Fee Rs 35 â€” the PTV licence fee collected through electricity bills. Applies to all domestic connections. There is no opt-out.",
          "Income Tax â€” withholding tax at 7.5% for unregistered consumers, 0% for filers. Filing your tax return removes this line entirely. Talk to a tax consultant if your annual electricity spend exceeds Rs 100,000 â€” the savings on income tax alone often pay for the consultant.",
          "Electricity Duty 1.5% â€” a provincial-government tax. Punjab applies 1.5%; rates differ in KPK, Sindh, and Balochistan.",
          "Financing Cost Surcharge (FC Surcharge) â€” a federally-mandated surcharge to repay circular debt accumulated by Pakistan's power sector. Currently around Rs 0.43 per unit. Applied uniformly across all consumers.",
          "Sales Tax + Further Tax â€” these are the small lines at the bottom. They are tied to the bill amount and are rounded to the nearest rupee.",
          "Total Payable â€” the bottom-line amount. The bill prints both the \"current bill\" and \"after due date\" amount. The second number includes a late-payment surcharge of 10% on the energy portion. Pay before the due date.",
        ],
        callout: {
          title: "Read your bill from the bottom up",
          body: "The most common reason for bill shock is the FPA line. Every time FPA spikes (it has spiked 5+ times since 2022), every consumer's bill goes up. Reading the bill bottom-up â€” look at the FPA per unit, multiply by your units, that's the surcharge â€” explains 80% of unexpected bill jumps.",
          variant: "info",
        },
      },
      {
        id: "tariff-overview",
        imageQuery: "electric grid transformer",
        heading: "MEPCO tariff structure â€” slab system explained",
        paragraphs: [
          "MEPCO's tariff is notified by NEPRA (National Electric Power Regulatory Authority) and is uniform across all 11 PITC DISCOs â€” Lahore, Faisalabad, Multan, Islamabad, Peshawar, Gujranwala, Hyderabad, Quetta, Sukkur, Tribal, and Hazara all charge identical per-unit rates for the same tariff code in the same slab. K-Electric in Karachi is the only DISCO with its own tariff, set separately by NEPRA. The full current table is on our MEPCO tariff page; the structure below explains what you are reading.",
          "Residential â€” protected (A-1a). Available to consumers whose six-month rolling average is at or below 200 units/month. Two micro-slabs: 1-100 units and 101-200 units. The per-unit rate is meaningfully lower than the unprotected slabs and the fixed charge is waived. To register for the protected slab, see the Cross Subsidy Program guide.",
          "Residential â€” unprotected (A-1b). The default for households whose average exceeds 200 units/month. Slabs at 1-100, 101-200, 201-300, 301-700, and above-700 units. The rates climb steeply across slabs and are non-telescopic at the top â€” once you cross into the above-700 slab, every single unit (not just the 701st onward) is priced at the highest rate. This non-telescopic switch is the single most-misunderstood rule in Pakistani electricity tariffs.",
          "Time-of-Use (ToU). Optional for residential consumers with a smart meter. Two periods: peak (typically 6 PM-10 PM in winter, 7 PM-11 PM in summer) and off-peak (the rest of the day). Peak units are priced higher; off-peak units are priced lower. ToU is mandatory for HT/EHT industrial connections. For most residential customers, opting into ToU saves money only if you can shift major loads (AC, washing machine, water pump) to off-peak hours.",
          "Commercial (A-2). Non-telescopic by design â€” every unit consumed is priced at the slab the total monthly consumption lands in, not graduated. A shop crossing from 99 to 100 units pays significantly more per unit on all 100 units. Two sub-categories by sanctioned load: A-2(a) under 5 kW, A-2(b) above 5 kW with separate ToU rates.",
          "Industrial (B). Multiple sub-categories: B-1 (low tension under 25 kW), B-2 (low tension over 25 kW), B-3 (medium tension), B-4 (high tension). Each has its own ToU schedule and demand-charge structure. B tariff customers pay a per-kVA demand charge in addition to the per-unit rate, which makes load-factor optimization more important than energy reduction for many factories.",
          "Agricultural (D). Available for tubewells and agricultural pumps. Heavily subsidised compared to A-1b. The catch is sanctioned-load reclassification: if a D-tariff tubewell is found running a domestic load, the meter is reclassified to A-1 retroactively for the last six months at the unprotected slab, plus a penalty.",
          "Beyond the slab table, three adjustments move the bill month-to-month: FPA (notified by NEPRA on the 15th of each month for the month two months prior), QTR adjustment (notified quarterly), and KE-specific surcharges (do not apply to MEPCO). The combined adjustments can add or subtract Rs 1-7 per unit relative to the base slab. Always read your bill's FPA and QTR lines before assuming your actual per-unit rate.",
        ],
      },
      {
        id: "payment-overview",
        imageQuery: "electricity bill statement",
        heading: "Payment methods â€” every approved channel and what to expect",
        paragraphs: [
          "MEPCO bills are payable through 30+ channels. The cheapest is always JazzCash or Easypaisa from a wallet balance â€” zero fees, instant settlement, and a digital receipt. The next-best is any bank's mobile app over 1Link, also zero fees and instant. Card payments through wallets typically carry a Rs 15-25 convenience fee. Cash counters at MEPCO offices and authorised bank branches are fee-free but require travel.",
          "JazzCash and Easypaisa are the dominant rails in southern Punjab â€” together they handle over 60% of MEPCO bill payments by volume. Open the app, go to Pay Bills, choose Electricity, choose MEPCO from the operator list, type the 14-digit reference, and confirm. The bill amount loads automatically; you cannot edit it. After payment a digital receipt with the transaction ID is sent to your registered mobile number. Save this â€” it is your proof of payment if the DISCO ever claims arrears.",
          "Bank apps work the same way through 1Link. HBL Mobile, UBL Digital, MCB Live, MeezanMobile, BankAlfalah Mobile, AlliedBank Mobile, FaysalMobile, BankIslamiMobile, AskariBank Mobile, BankAlHabibMobile, JS Bank Mobile, Soneri Mobile, Bank Al Habib, Habib Metropolitan, Summit Bank, Standard Chartered â€” all support MEPCO bill payment. The advantage of paying through a bank app over a wallet is that the payment goes from your bank account directly without first loading the wallet, which is faster for one-off bill payments.",
          "Auto-debit is available through any bank's standing instruction. Visit your branch with a copy of any recent bill and ask for an auto-debit standing instruction. The bank will debit your account 3-5 days before the bill due date each month and remit to MEPCO. There is no fee. The catch: standing instructions debit whatever amount MEPCO bills, including any spike â€” if your bill jumps from Rs 3,000 to Rs 30,000 because of a meter-reader error, the auto-debit still goes through. Most consumers prefer manual payment for this reason.",
          "Cash at MEPCO subdivision counters and authorised bank branches works for any reference. NBP, HBL, UBL, MCB, ABL, Bank of Punjab branches are the most common authorised collectors. The receipt prints immediately and is reflected in the MEPCO master within four working hours. For visa-application or rental documentation deadlines that require a stamped cash receipt, this is the only path.",
          "Cheque payment by drop-box exists at MEPCO subdivision offices for businesses that prefer it. The cheque must be account-payee and crossed; cash cheques are returned. Cheques clear in 2-3 working days; reflect in the master 24 hours after clearance.",
          "After-due-date payments include a 10% late-payment surcharge calculated on the energy-charge portion only. If you pay between the due date and the disconnection date (typically 7-15 days after), the surcharge applies but supply is not interrupted. After disconnection, a reconnection fee of Rs 200-1,000 (depending on tariff category) is added, payable before supply is restored.",
        ],
      },
      {
        id: "load-shedding",
        imageQuery: "electric power lines sunset",
        heading: "Load shedding in MEPCO territory â€” what to expect and where",
        paragraphs: [
          "MEPCO's territory covers 87,000 square kilometres of southern Punjab â€” from densely-populated urban Multan and Bahawalpur to remote villages in Rajanpur, Cholistan, and the Indus belt. Load shedding (planned rolling outages) is significantly heavier here than in the IESCO or LESCO territories. The pattern varies by feeder loss class: feeders with under 10% AT&C losses see 2-4 hours/day during peak summer; feeders with 10-20% losses see 4-8 hours; feeders with over 20% losses can see 10-14 hours/day in May-August.",
          "MEPCO publishes a daily load-shedding schedule on its website (mepco.com.pk â†’ Load Shedding Schedule) and on its official Facebook page. The schedule is by feeder name â€” find your feeder from your bill (it appears under \"Feeder\" near the tariff code) and look up its slot. Note that the official schedule is the planned schedule; actual outages can run longer due to grid faults, transformer trips, and emergency curtailments by the National Power Control Centre (NPCC).",
          "Unplanned outages cluster in May-July (pre-monsoon thermal stress on conductors), July-August (monsoon rain and lightning), and December-January (fog-related insulator faults). The MEPCO outage helpline 118 is operational 24x7. The most efficient way to report an outage is via the MEPCO Facebook page comment thread â€” the social-media team relays serious complaints to the local SDO within minutes. The 118 line is often saturated during peak monsoon hours.",
          "Solar UPS and inverter systems have become near-universal in MEPCO households earning Rs 50,000+/month, driven by exactly these load-shedding patterns. A typical 1.5 kW solar UPS handles 2-3 fans, 4-6 LEDs, a TV, and a WiFi router for the duration of a 4-hour outage; a 3 kW system adds a refrigerator and pumps. If you are considering solar, the more useful question is whether to add net-metering â€” see the next-connection spoke for the application flow.",
          "Two practical caveats. First, MEPCO does not compensate for outages affecting individual consumers below the threshold of compensation defined in NEPRA's Performance Standards Regulations. Second, prepaid meters operate as pay-as-you-go: if your meter is prepaid and the unit balance reaches zero during an outage, your supply remains off until you recharge â€” even if the local feeder is restored.",
        ],
      },
      {
        id: "complaints-overview",
        imageQuery: "electric power lines sunset",
        heading: "Complaints â€” the four-step escalation ladder",
        paragraphs: [
          "MEPCO complaint handling follows NEPRA's Standards of Performance Regulations 2021. The framework has four steps, with statutory turnaround days for each. Most billing disputes resolve at step 1; serious cases (overbilling, wrong tariff classification, prolonged outage compensation) usually need step 3 or 4.",
          "Step 1 â€” local subdivision SDO. The Subdivisional Officer is the closest MEPCO authority to your meter. Visit during office hours (typically 8 AM-3 PM, Monday-Friday) with your reference number and a brief written complaint. The SDO has the authority to correct meter-reader errors, adjust bills against meter testing, and issue a fresh bill within 7 working days. Always get an inward number stamped on your copy of the complaint â€” without it, the complaint does not exist in the MEPCO system.",
          "Step 2 â€” MEPCO General Manager Customer Services. If the SDO does not resolve within 15 days, escalate to the GM Customer Services at MEPCO Head Office, Khanewal Road, Multan. The GM must respond in writing within 30 working days. The escalation can be filed by post, by email to gm.cs@mepco.com.pk (or the current address on mepco.com.pk), or in person at the head office.",
          "Step 3 â€” Electric Inspector / NEPRA Regional Office. If MEPCO does not resolve at step 2, file with the Electric Inspector (Punjab) for Multan circle â€” office address on punjab.gov.pk â†’ Energy Department. The Electric Inspector is a quasi-judicial officer empowered to issue binding orders against MEPCO. Hearings are open, free of cost, and you can represent yourself. The Electric Inspector must dispose of the case within 90 days.",
          "Step 4 â€” NEPRA Head Office / Consumer Affairs Department. The final administrative escalation. NEPRA's Consumer Affairs Department in Islamabad accepts appeals against Electric Inspector orders and direct complaints in matters of policy (tariff disputes, regulatory misconduct). Appeals are filed within 60 days of the Electric Inspector's order. Beyond NEPRA, the only forum is the high court â€” and almost no consumer complaints reach that stage.",
        ],
      },
      {
        id: "cross-subsidy",
        imageQuery: "electric grid transformer",
        heading: "Cross Subsidy Program â€” how protected consumers get a lower bill",
        paragraphs: [
          "The Government of Pakistan's Cross Subsidy Program (CSS) lets verified low-usage domestic consumers register on css.pitc.com.pk to be classified as protected (A-1a) and receive the lower per-unit rate every month. The rules apply uniformly across MEPCO, LESCO, IESCO, FESCO, GEPCO, PESCO, HESCO, SEPCO, QESCO, TESCO, and HAZECO â€” K-Electric in Karachi has a separate program.",
          "Eligibility requires three intersecting conditions: a domestic (A-1) tariff classification, a six-month rolling average at or below 200 units/month, and only one live domestic connection per CNIC nationally. The registration takes under two minutes and is free; it requires the 14-digit reference, a CNIC, and a PTA biometric-verified mobile number for OTP.",
          "Once registered, the protected tariff reflects on your next bill cycle if you qualify. The subsidy is dynamic â€” every cycle PITC re-evaluates your rolling six-month average. If your usage exits the protected band, the subsidy pauses; once your average drops back, it resumes automatically.",
          "Read our full Cross Subsidy Program guide for the step-by-step registration, eligibility rules, expected savings, and a transparent walk-through of what the css.pitc.com.pk portal actually does behind the scenes.",
        ],
      },
      {
        id: "energy-saving",
        imageQuery: "electric power lines sunset",
        heading: "Practical energy-saving for MEPCO customers",
        paragraphs: [
          "The single highest-impact change for a southern Punjab household is the air conditioner. MEPCO's tariff slabs make every additional 100 units measurably more expensive per unit. Replacing a 3-star non-inverter AC with a 5-star inverter model typically cuts AC consumption by 30-40%. For a 1.5 ton AC running 8 hours/day from May to September, that's roughly 180 fewer units per month, which often drops the bill into a lower slab and amplifies the saving disproportionately.",
          "Refrigerators are the second-highest baseline load. A 1995-era refrigerator can draw 1,500 kWh/year; a 2024 5-star model of the same capacity draws 250-300 kWh/year. The replacement payback is typically 4-5 years on energy savings alone, faster if the old fridge is at end-of-life anyway.",
          "Geysers and water pumps are the third largest household load and the easiest to optimise. The 25-litre storage geyser in most southern Punjab bathrooms consumes about 3 kWh per heating cycle. Installing a timer that runs the geyser for the 30 minutes before your typical shower time â€” instead of leaving it on all morning â€” saves more units than any LED retrofit. The same logic applies to overhead-tank pumps: a smart float switch (any local electrician can install for Rs 2,500) saves 30-50 units/month relative to manually-controlled pumps.",
          "LED retrofits are the easiest energy intervention to over-rate. Replacing twelve 60-watt incandescent bulbs (used 4 hours/day) with 9-watt LEDs saves about 73 kWh/month, which is real money but is rarely the bill-defining change. Do it because it pays back in under a year, not because it transforms your bill.",
          "Solar net-metering deserves a separate analysis. A 3 kW rooftop solar system in Multan/Bahawalpur generates approximately 450-550 kWh/month (the south-Punjab insolation is among the highest in Pakistan), which for a household consuming 600 units would offset 75-90% of grid draw. Capital cost (2026) is about Rs 4-5 lakh after the federal subsidy for systems under 5 kW. Payback is in 4-6 years; the catch is that the application process through MEPCO and NEPRA takes 60-90 days and requires AEDB-registered installer paperwork. The new-connection spoke has the full application flow.",
        ],
      },
      {
        id: "smart-meters",
        imageQuery: "electric grid transformer",
        heading: "AMI smart meters under MEPCO's RDSS rollout",
        paragraphs: [
          "Under the Revamped Distribution Sector Scheme (RDSS), MEPCO has been installing 4G-enabled smart meters across high-loss feeders since 2023. The target is full smart-meter coverage by 2028. As of mid-2026, approximately 600,000 meters were live in the MEPCO network, concentrated in Multan urban, Bahawalpur urban, and a few high-loss rural feeders selected for early replacement.",
          "A smart meter changes three things from the consumer's perspective. First, the bill is generated automatically on the last day of the calendar month rather than on the day the meter-reader visits â€” meter-reader bribery and tampering disputes drop sharply. Second, the meter sends 15-minute interval data to MEPCO over LTE, which means you can theoretically opt into Time-of-Use tariff for savings. Third, MEPCO can remotely disconnect supply for non-payment and remotely reconnect after payment â€” the days of disconnection requiring an SDO technician visit are ending.",
          "Smart meters do not change your tariff slab â€” the per-unit rates are the same as for conventional meters. They do open up optional ToU tariff for residential consumers, which is what makes the meter financially useful for households that can shift large loads (water pumps, washing machines) to off-peak hours.",
          "If you have a complaint about your smart meter â€” sudden spikes in consumption, the meter not reporting, the display blanking out â€” log a ticket on the MEPCO app or call 118. NEPRA's Standards of Performance require MEPCO to send a technician within 48 hours for a metering complaint at a residential premise.",
        ],
      },
      {
        id: "name-change",
        imageQuery: "electric grid transformer",
        heading: "Name change, transfer of ownership, and refund of security deposit",
        paragraphs: [
          "When you buy a house in MEPCO territory or inherit a connection, the meter does not automatically transfer to your name. The previous owner's name stays on the bill until you formally apply for a Change of Name (CON). The application is filed at your local MEPCO subdivision; documents include sale deed or transfer letter, both buyer's and seller's CNICs, the previous month's paid bill, and a Rs 200 application fee.",
          "The CON process officially takes 15 working days per NEPRA's Standards of Performance. In practice it is faster if the property paperwork is clean and slower if there are arrears or pending complaints on the connection. Tip: pay any arrears before applying for CON â€” otherwise the application is parked until arrears clear.",
          "Transfer of security deposit is automatic with CON. The previous owner's deposit (typically Rs 500-2,500 for residential connections, paid at the time of original connection) transfers to your account and continues to accrue interest at the rate notified by NEPRA each year. The deposit is refundable when the connection is permanently disconnected. If you do not want to take over the previous deposit, you can pay a fresh deposit and the previous owner can claim a refund from MEPCO â€” useful when the previous deposit is very old and has grown with interest.",
          "Tenants: you do not need a CON if you are renting. The connection stays in the landlord's name; you simply pay the bill. Some landlords add an address-of-bill change so the bill PDF is emailed to the tenant, but the legal liability for non-payment stays with the named consumer. This is the standard arrangement for short-term rentals.",
        ],
      },
    ],
    faq: [
      { q: "What is the MEPCO reference number and where do I find it?", a: "The MEPCO reference is a 14-digit identifier printed at the top-right of every bill. It is the only number you need to view, download, or pay your bill online â€” no login is required. If your printed bill is damaged, you can recover the reference by visiting your nearest MEPCO subdivision with your CNIC; they will print a fresh duplicate in five minutes." },
      { q: "Where does MEPCO supply electricity?", a: "MEPCO serves 13 districts in southern Punjab: Multan, Bahawalpur, Dera Ghazi Khan, Sahiwal, Vehari, Lodhran, Khanewal, Muzaffargarh, Rahim Yar Khan, Bahawalnagar, Rajanpur, Pakpattan, and Layyah. About 7.6 million consumers total, covering 87,000 square kilometres." },
      { q: "What is the MEPCO customer-care number?", a: "Universal DISCO helpline 118 (toll-free, 24x7). For non-emergency queries, the MEPCO complaint cell at Head Office Khanewal Road, Multan, accepts written complaints and emails to gm.cs@mepco.com.pk (current address on mepco.com.pk)." },
      { q: "Why is my MEPCO bill higher than last month?", a: "Three usual causes. First, slab transition: crossing from 200 to 201 units moves you out of the protected slab. Second, FPA adjustment: the Fuel Price Adjustment can swing a bill 10-25% in either direction month to month. Third, meter-reader error â€” photograph your meter today, compare the reading on it to the \"Current Reading\" printed on the bill. If they don't match, call 118 with both numbers ready." },
      { q: "Can I pay my MEPCO bill with JazzCash or Easypaisa?", a: "Yes â€” both wallets support MEPCO bill payment under Pay Bills â†’ Electricity â†’ MEPCO. Zero fees from wallet balance, instant settlement, and a digital receipt sent to your mobile. This is the fastest path from bill view to payment." },
      { q: "How long does it take for MEPCO bill payment to reflect?", a: "JazzCash, Easypaisa, and bank-app payments via 1Link settle instantly (under 30 seconds). Cash payments at MEPCO subdivision and authorised bank branches reflect in 4 working hours. Cheque payments clear in 2-3 working days." },
      { q: "What if my MEPCO bill is wrong?", a: "Visit your local subdivision SDO first with the bill in hand. The SDO can correct meter-reader errors, adjust bills against meter testing, and issue a fresh bill within 7 working days. If unresolved in 15 days, escalate to GM Customer Services at MEPCO Head Office in Multan." },
      { q: "How do I apply for the protected tariff (lower bill)?", a: "Register on the Cross Subsidy Program at css.pitc.com.pk. Eligibility requires a six-month rolling average at or below 200 units/month, an A-1 domestic tariff, and only one live connection per CNIC nationally. See our Cross Subsidy Program guide for the step-by-step." },
      { q: "Does MEPCO send bills by email?", a: "MEPCO does not send bills by email by default. The MEPCO mobile app lets you opt into PDF email notifications (free). Alternatively, you can download a PDF anytime from this page using your reference number â€” the PDF carries the PITC verification stamp and is accepted as proof of address by banks and NADRA." },
      { q: "What is the MEPCO load-shedding schedule today?", a: "MEPCO publishes its daily schedule on mepco.com.pk â†’ Load Shedding Schedule and on its official Facebook page. The schedule is by feeder name (find yours from the \"Feeder\" field on your bill). Unplanned outages on top of the schedule are tracked on the same Facebook page and via the 118 helpline." },
      { q: "Can I apply for a new MEPCO connection online?", a: "Yes â€” MEPCO accepts new-connection applications online via mepco.com.pk â†’ New Connection. You upload ownership/rental documents, CNIC, address proof, and a photo of the proposed meter location. MEPCO schedules a site visit within 5 working days, issues a load estimate, and after deposit payment the meter is energised within 30 working days for single-phase under 5 kW." },
      { q: "What is the MEPCO security deposit?", a: "Residential single-phase under 5 kW: Rs 500-2,500 depending on sanctioned load. Three-phase: Rs 5,000-15,000. Commercial and industrial: load-dependent, can run into lakhs. All deposits are refundable on permanent disconnection and accrue interest at the rate notified by NEPRA each year." },
      { q: "How do I correct the name on my MEPCO bill?", a: "Apply for a Change of Name (CON) at your local MEPCO subdivision with sale deed or transfer letter, both buyer's and seller's CNICs, the previous month's paid bill, and a Rs 200 fee. Officially 15 working days; in practice 7-21 days if paperwork is clean and arrears are paid first." },
      { q: "Does MEPCO offer net-metering for rooftop solar?", a: "Yes. Net-metering applications go through MEPCO and require AEDB-registered installer paperwork. End-to-end timeline is 60-90 days including witness testing. Residential systems up to 25 kW are eligible. See the new-connection spoke for the full application flow." },
      { q: "Is MEPCO connected to K-Electric?", a: "No. MEPCO is one of 11 DISCOs that bill through PITC (bill.pitc.com.pk); K-Electric is a separate company that bills through its own portal at ke.com.pk. The tariff structures, complaint procedures, and bill formats are different. If you have moved from Karachi to Multan (or vice versa) you will need a new connection in your new DISCO's territory." },
    ],
    citations: [
      { label: "NEPRA Tariff Schedule for XWDISCOs (current)", url: "https://nepra.org.pk/tariff/Tariff%20XWDISCOs.html", retrievedOn: "2026-04-30" },
      { label: "MEPCO official website", url: "https://www.mepco.com.pk/", retrievedOn: "2026-05-09" },
      { label: "PITC unified DISCO portal", url: "https://bill.pitc.com.pk/mepcobill", retrievedOn: "2026-05-09" },
      { label: "NEPRA Performance Standards (Distribution) Rules 2005, amended 2021", url: "https://nepra.org.pk/", retrievedOn: "2026-03-21" },
      { label: "NEPRA Consumer Service Manual 2021", url: "https://nepra.org.pk/", retrievedOn: "2026-03-21" },
    ],
    lastReviewed: "2026-05-19",
    author: "CheckBillsOnline Editorial",
    tariff: {
      caption: "MEPCO residential tariff â€” domestic A-1 slab rates, current FY",
      sourceLabel: "NEPRA Tariff Schedule for XWDISCOs",
      sourceUrl: "https://nepra.org.pk/tariff/Tariff%20XWDISCOs.html",
      retrievedOn: "2026-04-30",
      rows: [
        { range: "0-100 units (protected A-1a)",     rate: "Rs 7.74",  unit: "/ kWh", notes: "Lifeline slab. Available only to CSS-registered consumers." },
        { range: "101-200 units (protected A-1a)",   rate: "Rs 10.06", unit: "/ kWh", notes: "Lifeline slab â€” second micro-band." },
        { range: "0-100 units (unprotected A-1b)",   rate: "Rs 16.48", unit: "/ kWh", notes: "Default residential slab." },
        { range: "101-200 units (unprotected A-1b)", rate: "Rs 22.95", unit: "/ kWh", notes: "Crossing 200 units removes you from protected eligibility." },
        { range: "201-300 units",                    rate: "Rs 27.14", unit: "/ kWh", notes: "Telescopic up to this point." },
        { range: "301-700 units",                    rate: "Rs 32.03", unit: "/ kWh", notes: "Largest residential slab range." },
        { range: "Above 700 units",                  rate: "Rs 35.24", unit: "/ kWh", notes: "Non-telescopic: every unit billed at this rate, not graduated." },
        { range: "Fixed Charge (residential)",       rate: "Rs 200-400", unit: "/ month", notes: "Slab-dependent; protected consumers exempt." },
        { range: "FPA (Fuel Price Adjustment)",      rate: "varies",   unit: "/ kWh", notes: "Notified by NEPRA on the 15th of each month for two months prior." },
        { range: "GST",                              rate: "17%",      unit: "of bill total ex-tax", notes: "Federal General Sales Tax." },
        { range: "TV Fee",                           rate: "Rs 35",    unit: "/ month", notes: "PTV licence; flat for all domestic connections." },
      ],
    },
    paymentMethods: [
      { name: "JazzCash",        category: "Wallet",       description: "Pay from JazzCash wallet balance via Pay Bills â†’ Electricity â†’ MEPCO. Settles in seconds, digital receipt by SMS.", url: "https://www.jazzcash.com.pk/", feeNote: "Free from wallet balance" },
      { name: "Easypaisa",       category: "Wallet",       description: "Same flow as JazzCash. Easypaisa is dominant in southern Punjab.", url: "https://easypaisa.com.pk/", feeNote: "Free from wallet balance" },
      { name: "Bank mobile apps",category: "Bank",         description: "HBL, UBL, MCB, Meezan, Allied, Bank Alfalah, Faysal, Bank Al Habib, JS, Soneri, Askari, all support MEPCO via 1Link.", feeNote: "Free" },
      { name: "1Link USSD *786#",category: "SMS",          description: "USSD bill payment from any 1Link bank account. Works on feature phones without data.", feeNote: "Free" },
      { name: "MEPCO subdivision counter (cash)", category: "Cash", description: "Cash at any MEPCO customer-service centre. Stamped receipt printed at counter.", feeNote: "Free" },
      { name: "NBP / HBL / UBL / MCB branches (cash)", category: "Bank", description: "Authorised utility-bill collection branches. Cash, pay-order, or cheque accepted.", feeNote: "Free" },
      { name: "Auto-debit (bank standing instruction)", category: "Bank", description: "Visit your bank branch with a recent bill to set up; bank debits 3-5 days before due date.", feeNote: "Free" },
      { name: "NadraPay / SadaPay / NayaPay", category: "Mobile app", description: "Newer fintech wallets all support MEPCO bill payment.", feeNote: "Free from wallet" },
    ],
    complaintsLadder: [
      { level: 1, body: "Local subdivision SDO",              contact: "Visit your nearest MEPCO subdivision office with reference number + brief written complaint. Get inward stamp.", turnaroundDays: 15 },
      { level: 2, body: "MEPCO GM Customer Services",         contact: "MEPCO Head Office, Khanewal Road, Multan Â· gm.cs@mepco.com.pk (verify current address on mepco.com.pk)", turnaroundDays: 30 },
      { level: 3, body: "Electric Inspector Punjab (Multan)", contact: "Office of the Electric Inspector, Punjab Energy Department, Multan circle. Free quasi-judicial hearings.", turnaroundDays: 90 },
      { level: 4, body: "NEPRA Consumer Affairs (Islamabad)", contact: "NEPRA Tower, Atta-Turk Avenue (East), G-5/1, Islamabad Â· consumer.affairs@nepra.org.pk", turnaroundDays: 90 },
    ],
  },

  spokes: {
    tariff: {
      metaTitle: "MEPCO Tariff â€” Slab Rates, FPA, QTR & All Bill Components Explained",
      metaDescription:
        "Full MEPCO residential and commercial tariff slabs notified by NEPRA. Protected vs unprotected, FPA explained, QTR adjustment, GST, electricity duty, and a worked example for each slab.",
      h1: "MEPCO tariff â€” slab rates, surcharges, and the math behind your bill",
      intro:
        "This is the full breakdown of MEPCO's NEPRA-notified tariff, with every per-unit rate and every surcharge explained. Tariff numbers are uniform across all 11 PITC DISCOs â€” what you read here applies identically in LESCO, IESCO, FESCO, GEPCO, PESCO, HESCO, SEPCO, QESCO, TESCO, and HAZECO. We refresh this page every time NEPRA issues a fresh order.",
      sections: [
        { id: "structure",
          imageQuery: "electric grid transformer",
          heading: "Tariff structure â€” which slab am I in?",
          paragraphs: [
            "Domestic tariff has two parallel tracks: A-1a (protected) and A-1b (unprotected). Your tariff code on the bill â€” printed near the consumer name â€” tells you which one you are on. Protected requires Cross Subsidy registration; unprotected is the default.",
            "Within each track, the slabs are telescopic up to 700 units: the first 100 units are billed at the 0-100 rate, the next 100 at the 101-200 rate, and so on. Above 700 units the tariff becomes non-telescopic â€” every unit consumed in the cycle is billed at the highest slab rate, not graduated. This jump at 700 is the single most-misunderstood rule in Pakistani residential tariffs and is the reason many high-consumption households see disproportionate bill spikes.",
            "Commercial (A-2) and industrial (B) tariffs are non-telescopic by design â€” every unit is priced at the slab the monthly total lands in. Be aware of this when crossing slab thresholds.",
          ] },
        { id: "protected",
          imageQuery: "electric power lines sunset",
          heading: "Protected slab (A-1a) â€” the lifeline tariff",
          paragraphs: [
            "Available only to consumers registered on the Cross Subsidy Program at css.pitc.com.pk. Requires a six-month rolling average at or below 200 units/month, an A-1 domestic tariff classification, and only one live connection per CNIC nationally.",
            "Two micro-bands within protected: 0-100 units and 101-200 units. The fixed charge is waived. The FPA pass-through is often softer for protected slabs depending on the monthly NEPRA notification.",
            "Once registered, the protected status is dynamic: every cycle PITC re-evaluates your rolling average. A single 250-unit month does not remove you (one spike against five low months still averages below 200), but two consecutive high months will push your average over and the subsidy pauses.",
          ] },
        { id: "unprotected",
          imageQuery: "electric power lines sunset",
          heading: "Unprotected slab (A-1b) â€” the default residential tariff",
          paragraphs: [
            "The default for any household without a CSS registration or with average above 200 units/month. Six slabs: 1-100, 101-200, 201-300, 301-400, 401-500, 501-700, and above-700.",
            "The protected vs unprotected delta at the 0-100 slab is meaningful â€” protected at Rs 7.74/unit vs unprotected at Rs 16.48/unit means the same 100 units cost Rs 774 protected and Rs 1,648 unprotected. Across a year of 100-unit months that is a Rs 10,488 saving â€” easily worth the 2-minute CSS registration.",
            "The non-telescopic jump above 700 units is the kicker. A household consuming 699 units pays Rs 32.03/unit on the 301-700 portion (398 units at that rate); a household consuming 701 units pays Rs 35.24 on all 701 units. Crossing this line carries a Rs 1,500-2,500 step-up in the bill that does not show up in any slab arithmetic â€” plan summer AC use accordingly.",
          ] },
        { id: "tou",
          imageQuery: "electric grid transformer",
          heading: "Time-of-Use (ToU) tariff",
          paragraphs: [
            "ToU is mandatory for HT and EHT industrial connections (B-3, B-4). Optional for residential consumers with a smart meter â€” and given MEPCO's RDSS smart-meter rollout is at ~600,000 meters and growing, more residential consumers are eligible every month.",
            "Two periods: peak (6 PM-10 PM in winter, 7 PM-11 PM in summer) and off-peak (the rest of the day). Peak units are priced higher; off-peak lower. The breakeven depends on your daily load profile â€” households with heavy evening AC use rarely save on ToU; households whose washing machine and water pump run at night usually do.",
          ] },
        { id: "fpa",
          imageQuery: "electric grid transformer",
          heading: "FPA â€” Fuel Price Adjustment, the most volatile line on your bill",
          paragraphs: [
            "FPA is a monthly pass-through that compensates for changes in the cost of generation between when NEPRA set the base tariff and when the bill is issued. NEPRA notifies the FPA on the 15th of each month, retrospectively for the month two months prior. So the FPA appearing on your May bill is the FPA for March consumption, calculated against March fuel costs.",
            "FPA can be positive or negative. In the high-FPA quarters of 2022-2023 it added Rs 4-7 per unit; in the low-FPA quarters of 2024 it was sometimes negative (a small refund). The annualised FPA is the single largest variable in residential bill spikes.",
            "FPA can be disputed only on arithmetic grounds â€” NEPRA's formula is approved and not appealable at the consumer level. If the FPA on your bill does not match the per-unit FPA Ã— your units consumed, file a complaint at step 1 (SDO).",
          ] },
        { id: "qtr",
          imageQuery: "electric grid transformer",
          heading: "QTR â€” Quarterly Tariff Adjustment",
          paragraphs: [
            "QTR is a quarterly true-up notification by NEPRA, reconciling the previous quarter's actual generation cost against the tariff. Like FPA but lumpier; some quarters QTR is positive, others negative.",
            "QTR typically appears on bills for 1-3 months after each notification. Read the QTR line carefully â€” it is the line where bill amounts can swing sharply month-to-month even with stable consumption.",
          ] },
        { id: "duty-gst",
          imageQuery: "electric grid transformer",
          heading: "Electricity Duty, GST, and other statutory levies",
          paragraphs: [
            "Punjab Electricity Duty is 1.5% of the energy charge. Sindh, KPK, and Balochistan apply different rates. The duty is a provincial-government levy independent of the federal tariff.",
            "GST is 17% federally (18% on commercial in some districts). The base is the bill total before income tax and electricity duty.",
            "TV Fee is a flat Rs 35 per residential connection, regardless of consumption. The PTV licence cannot be opted out.",
            "Income Tax withholding is 7.5% for unregistered consumers, 0% for filers. The single largest reason for non-filers to consider filing a tax return is the 7.5% withholding on electricity bills â€” for a household with a Rs 300,000 annual electricity spend, filing saves Rs 22,500/year.",
            "Financing Cost Surcharge (FC) is currently around Rs 0.43 per unit and funds repayment of the power sector's circular debt. Applied uniformly.",
          ] },
      ],
      faq: [
        { q: "Where can I download the current NEPRA tariff schedule?", a: "nepra.org.pk â†’ Tariff â†’ XWDISCOs publishes the consolidated tariff schedule for all 11 PITC DISCOs. The PDF is updated each tariff cycle and is the authoritative source." },
        { q: "Why does my bill's FPA line look wrong?", a: "FPA is calculated as (FPA per unit) Ã— (units consumed). If the multiplication does not match, file a complaint at step 1 (your subdivision SDO). The FPA formula itself is approved by NEPRA and not disputable at the consumer level." },
        { q: "Can I switch from unprotected to protected if I am eligible?", a: "Yes â€” register on the Cross Subsidy Program at css.pitc.com.pk. Eligibility requires a six-month rolling average at or below 200 units/month, an A-1 tariff, and one live connection per CNIC. See our Cross Subsidy Program guide." },
        { q: "Is there a residential tariff for working-from-home households?", a: "No specific tariff exists for work-from-home households. If you have a separate room dedicated to a business with high load (multiple computers, AC), MEPCO may reclassify the meter to commercial; in that case ask for a separate meter for the business portion to keep the residential meter on A-1." },
      ],
      citations: [
        { label: "NEPRA Tariff Schedule for XWDISCOs", url: "https://nepra.org.pk/tariff/Tariff%20XWDISCOs.html", retrievedOn: "2026-04-30" },
        { label: "NEPRA monthly FPA notifications", url: "https://nepra.org.pk/", retrievedOn: "2026-04-30" },
      ],
      lastReviewed: "2026-04-30",
      author: "CheckBillsOnline Editorial",
      tariff: undefined,
    },

    "payment-methods": {
      metaTitle: "MEPCO Bill Payment â€” JazzCash, Easypaisa, Banks, Cash (All Channels)",
      metaDescription:
        "Every way to pay your MEPCO bill â€” JazzCash, Easypaisa, NayaPay, SadaPay, bank apps via 1Link, USSD *786#, cash at MEPCO and bank branches, and auto-debit. Fees, settle times, and which is fastest.",
      h1: "MEPCO bill payment â€” every working method, with fees and settle times",
      intro:
        "MEPCO bills are payable through 30+ channels. JazzCash and Easypaisa together handle over 60% of southern Punjab's MEPCO bill payments by volume. This page walks through each method with its settle time and current fee structure, in order from cheapest-and-fastest to slowest.",
      sections: [
        { id: "wallets",
          imageQuery: "electricity bill statement",
          heading: "Mobile wallets â€” JazzCash, Easypaisa, NayaPay, SadaPay",
          paragraphs: [
            "JazzCash is the largest wallet in Pakistan with over 50 million accounts. Open the app â†’ Pay Bills â†’ Electricity â†’ MEPCO â†’ enter the 14-digit reference. The bill amount loads automatically (you cannot edit it). Confirm and the payment settles in seconds. Zero fees from wallet balance. Digital receipt SMS to your registered mobile.",
            "Easypaisa is the second-largest and is the dominant wallet in southern Punjab. The flow is identical to JazzCash. Easypaisa receipts include a Transaction ID that the MEPCO master uses to reconcile payment â€” save the SMS for at least three months.",
            "NayaPay and SadaPay are the newer fintech wallets. Same flow under their respective Bill Payment sections. Both are interoperable with the 1Link rail so your payment hits MEPCO at the same speed as JazzCash and Easypaisa.",
          ] },
        { id: "banks",
          imageQuery: "electricity bill statement",
          heading: "Bank mobile apps via 1Link",
          paragraphs: [
            "Every major Pakistani bank's mobile app supports MEPCO bill payment over 1Link. HBL Mobile, UBL Digital, MCB Live, Meezan Mobile, Allied Bank Mobile, Bank Alfalah Mobile, Faysal Mobile, Bank Al Habib Mobile, JS Bank Mobile, Soneri Mobile, Askari Bank Mobile, Habib Metropolitan Mobile, Summit Bank Mobile, Standard Chartered Pakistan Mobile, Bank Islami Mobile, Silk Bank Mobile, and Bank of Punjab Mobile all support MEPCO bill payment.",
            "The flow is the same in every app: Pay Bills â†’ Electricity â†’ MEPCO â†’ enter reference. The bill amount loads from PITC automatically. Confirm with your transaction PIN or biometric.",
            "Bank-app payments settle instantly (under 30 seconds) and carry no fee. They are the recommended option for one-off payments because the money goes from your bank directly without first loading a wallet.",
          ] },
        { id: "ussd",
          imageQuery: "electricity bill statement",
          heading: "1Link USSD *786# â€” pay from a feature phone",
          paragraphs: [
            "USSD *786# from any 1Link-member bank account works on a basic feature phone with no internet. Dial *786#, choose Pay Bills, choose Electricity, choose MEPCO, enter reference, confirm with PIN. The USSD menu walks through every step in plain English (Urdu is also available on most operators).",
            "Useful in rural pockets of MEPCO territory where smartphone penetration is low and 2G coverage is the norm. The fee is zero from your bank account; standard USSD session charges apply (Rs 0-2 depending on operator).",
          ] },
        { id: "cash",
          imageQuery: "electricity bill statement",
          heading: "Cash payment at counters",
          paragraphs: [
            "MEPCO accepts cash at all 320+ subdivision and customer-service centres. Bring the bill and the cash; the counter clerk processes the payment and prints a stamped receipt within minutes. The receipt is reflected in the MEPCO master within four working hours â€” useful for time-sensitive documentation deadlines.",
            "Authorised bank branches that accept utility-bill cash payments include NBP, HBL, UBL, MCB, ABL, and Bank of Punjab branches. Look for the \"Utility Bill Payment\" sign on the branch. Counter hours are typically 9 AM-1 PM, Monday-Friday.",
            "Cash payments at supermarkets and convenience stores (Imtiaz, Carrefour, Hyperstar) work for MEPCO bills but usually carry a small handling fee (Rs 5-20). Useful at odd hours when bank branches are closed.",
          ] },
        { id: "auto-debit",
          imageQuery: "electricity bill statement",
          heading: "Auto-debit standing instruction",
          paragraphs: [
            "Any bank can set up a standing instruction to auto-debit your MEPCO bill 3-5 days before the due date. Visit your branch with a copy of a recent bill and your CNIC. The bank notes the 14-digit reference, sets the standing instruction, and from the next cycle the bill is debited automatically.",
            "No fee. The catch: standing instructions debit whatever amount MEPCO bills, including any spike. If your bill jumps from Rs 3,000 to Rs 30,000 because of a meter-reader error, the auto-debit still goes through. Most consumers prefer manual payment for this reason.",
            "If you want a hybrid â€” auto-debit up to a ceiling, manual review above â€” most banks offer a \"variable standing instruction\" with a maximum amount. Bills above the ceiling fail the auto-debit and notify you to pay manually.",
          ] },
        { id: "after-due-date",
          imageQuery: "electricity bill statement",
          heading: "After due date â€” surcharges and disconnection",
          paragraphs: [
            "If you pay between the due date and the disconnection date (typically 7-15 days after the due date), a 10% late-payment surcharge on the energy-charge portion applies. The disconnection date is printed on the bill.",
            "Supply is disconnected after the disconnection date if no payment has reached MEPCO. Reconnection requires payment of the outstanding bill plus a reconnection fee (Rs 200-1,000 depending on tariff category) plus, on conventional meters, an SDO technician visit. On smart meters reconnection is remote and instant after payment.",
            "Disputed bills can be paid \"under protest\" using the same channels â€” the payment lifts the disconnection risk while the dispute is resolved. Adjustments approved by the SDO or higher are reflected as credits on subsequent bills.",
          ] },
      ],
      paymentMethods: [
        { name: "JazzCash",        category: "Wallet",       description: "Pay from JazzCash wallet via Pay Bills â†’ Electricity â†’ MEPCO. Settles in seconds.", url: "https://www.jazzcash.com.pk/", feeNote: "Free from wallet" },
        { name: "Easypaisa",       category: "Wallet",       description: "Pay from Easypaisa wallet. Dominant in southern Punjab.", url: "https://easypaisa.com.pk/", feeNote: "Free from wallet" },
        { name: "NayaPay / SadaPay", category: "Wallet",     description: "Newer fintech wallets, same flow.", feeNote: "Free" },
        { name: "Bank mobile apps",category: "Bank",         description: "Every major Pakistani bank's app supports MEPCO over 1Link.", feeNote: "Free" },
        { name: "1Link USSD *786#",category: "SMS",          description: "USSD from any 1Link bank account; works on feature phones.", feeNote: "Free + USSD charges" },
        { name: "MEPCO counters (cash)", category: "Cash", description: "320+ subdivision counters across southern Punjab.", feeNote: "Free" },
        { name: "NBP / HBL / UBL / MCB / ABL / BoP branches (cash)", category: "Bank", description: "Authorised utility-bill collection branches.", feeNote: "Free" },
        { name: "Auto-debit", category: "Bank", description: "Standing instruction at any bank.", feeNote: "Free" },
      ],
      faq: [
        { q: "Which payment method has the lowest fee?", a: "JazzCash, Easypaisa, NayaPay, SadaPay from wallet balance, and any bank mobile app via 1Link â€” all zero fee, all instant settlement." },
        { q: "How do I cancel auto-debit?", a: "Visit the bank branch that set up the standing instruction with your CNIC. Auto-debit cancellation takes one working day to reflect." },
        { q: "Can I pay a MEPCO bill from outside Pakistan?", a: "Yes â€” bank apps work for any account holder regardless of physical location, as long as you have access to your Pakistani bank's mobile app. JazzCash and Easypaisa require a Pakistani SIM for OTP confirmation." },
      ],
      citations: [
        { label: "1Link bill payment", url: "https://www.1link.net.pk/", retrievedOn: "2026-05-01" },
        { label: "JazzCash Bill Payment", url: "https://www.jazzcash.com.pk/", retrievedOn: "2026-05-01" },
        { label: "Easypaisa Bill Payment", url: "https://easypaisa.com.pk/", retrievedOn: "2026-05-01" },
      ],
      lastReviewed: "2026-05-01",
      author: "CheckBillsOnline Editorial",
    },

    complaints: {
      metaTitle: "MEPCO Complaints â€” SDO, GM CS, Electric Inspector, NEPRA Escalation",
      metaDescription:
        "Step-by-step complaint escalation for MEPCO. SDO, GM Customer Services, Electric Inspector Punjab, NEPRA Consumer Affairs â€” with statutory turnaround days and template letters.",
      h1: "MEPCO complaints â€” the four-step escalation ladder",
      intro:
        "NEPRA's Standards of Performance Regulations 2021 and the Consumer Service Manual 2021 together prescribe a four-step escalation procedure. This page walks through each step with current contacts, statutory turnaround days, and what each forum is empowered to do.",
      sections: [
        { id: "step1-sdo",
          imageQuery: "electric power lines sunset",
          heading: "Step 1 â€” Local subdivision SDO",
          paragraphs: [
            "The Subdivisional Officer (SDO) is the closest MEPCO authority to your meter. Every locality has an SDO office; the address is printed on your bill under \"Subdivision\".",
            "Visit during office hours (typically 8 AM-3 PM, Monday-Friday) with your reference number, the bill you are disputing, and a brief written complaint. The SDO has authority to correct meter-reader errors, adjust bills against meter testing, issue a fresh bill within 7 working days, and waive small surcharges. Always get an inward number stamped on your copy of the complaint â€” without it, the complaint does not exist in the MEPCO system.",
            "If the SDO does not resolve within 15 days, automatic escalation to step 2 is your right. You also have the right to escalate yourself at any time after 15 days.",
          ] },
        { id: "step2-gmcs",
          imageQuery: "electric power lines sunset",
          heading: "Step 2 â€” MEPCO GM Customer Services",
          paragraphs: [
            "The General Manager Customer Services at MEPCO Head Office, Khanewal Road, Multan handles formal escalations from SDOs. File by post, by email to gm.cs@mepco.com.pk (verify current address on mepco.com.pk), or in person at the head office.",
            "The GM CS must respond in writing within 30 working days. The response typically directs the local SDO to take a specific action, refers the matter to the Meter Testing Lab, or proposes a settlement.",
            "Tip: attach copies of every paper trail to your GM CS letter â€” the original bill, your stamped SDO complaint, the SDO's response or lack thereof, and any photographic evidence (meter readings, damaged seal, etc.). The more documented the file, the faster the resolution.",
          ] },
        { id: "step3-electric-inspector",
          imageQuery: "electric power lines sunset",
          heading: "Step 3 â€” Electric Inspector Punjab (Multan circle)",
          paragraphs: [
            "The Electric Inspector is a quasi-judicial officer of the Punjab Energy Department, empowered to issue binding orders against MEPCO. The Multan circle office address is on punjab.gov.pk â†’ Energy Department.",
            "Hearings are open, free of cost, and you can represent yourself. Documents: the original bill, your written complaint trail, copies of relevant tariff orders or regulations. The Electric Inspector must dispose of the case within 90 days.",
            "Common matters: meter testing disputes (the Electric Inspector can order MEPCO to conduct an accredited third-party test), overbilling refunds, wrong tariff classification, and prolonged outage compensation. The Inspector's orders are appealable to NEPRA.",
          ] },
        { id: "step4-nepra",
          imageQuery: "electric power lines sunset",
          heading: "Step 4 â€” NEPRA Consumer Affairs",
          paragraphs: [
            "NEPRA's Consumer Affairs Department in Islamabad is the final administrative escalation. NEPRA Tower, Atta-Turk Avenue (East), G-5/1, Islamabad. Email: consumer.affairs@nepra.org.pk.",
            "Two categories of cases: appeals against Electric Inspector orders (filed within 60 days of the Inspector's order), and direct complaints in matters of policy (tariff disputes, regulatory misconduct).",
            "NEPRA must dispose of cases within 90 days. Beyond NEPRA, the only forum is the high court â€” and almost no consumer complaints reach that stage.",
          ] },
        { id: "common-complaints",
          imageQuery: "electric power lines sunset",
          heading: "Common MEPCO complaints and the right escalation level",
          paragraphs: [
            "Meter-reader error (estimated reading, photo evidence, or detector reading mismatch): Step 1, SDO â€” almost always resolved here.",
            "Wrong tariff classification (residential meter billed as commercial): Step 1, SDO â€” if denied, Step 3, Electric Inspector with copies of property documents.",
            "Overbilling on FPA or QTR (arithmetic dispute): Step 1, SDO â€” must be a documented arithmetic mismatch, not a dispute of the FPA rate itself.",
            "Disconnection without notice or wrongful disconnection: Step 1, SDO with photographic timestamp evidence â€” escalate to Step 3 if not resolved in 7 days.",
            "Damaged or burnt-out service line (low-voltage hazard): emergency line 118 immediately â€” also file a written Step 1 complaint for the formal record.",
            "Outage compensation (prolonged unplanned outage exceeding NEPRA SoP thresholds): Step 1, SDO with outage log evidence â€” escalate to Step 3 for binding order.",
          ] },
      ],
      ladder: [
        { level: 1, body: "Local subdivision SDO",              contact: "Visit subdivision office with bill + brief written complaint. Get inward stamp.", turnaroundDays: 15 },
        { level: 2, body: "MEPCO GM Customer Services",         contact: "Head Office, Khanewal Road, Multan Â· gm.cs@mepco.com.pk", turnaroundDays: 30 },
        { level: 3, body: "Electric Inspector Punjab (Multan)", contact: "Punjab Energy Department, Multan circle", turnaroundDays: 90 },
        { level: 4, body: "NEPRA Consumer Affairs",             contact: "NEPRA Tower, G-5/1, Islamabad Â· consumer.affairs@nepra.org.pk", turnaroundDays: 90 },
      ],
      faq: [
        { q: "Is the Electric Inspector a court?", a: "It is a quasi-judicial forum under the Electricity Act 1910 and the Punjab Provincial Electricity Inspectorate Act. Orders are binding on MEPCO but appealable to NEPRA." },
        { q: "Do I need a lawyer at the Electric Inspector?", a: "No. You can represent yourself; most consumer complaints are heard without lawyers." },
        { q: "Is there a fee to file at the Electric Inspector or NEPRA?", a: "No fee at either forum. Both are free for the consumer." },
        { q: "How long does the full escalation take if I have to go all the way?", a: "Step 1 (15) + Step 2 (30) + Step 3 (90) + Step 4 (90) = 225 days maximum. Most cases resolve at Step 1 or 2 within 30-45 days." },
      ],
      citations: [
        { label: "NEPRA Standards of Performance Regulations 2021", url: "https://nepra.org.pk/", retrievedOn: "2026-03-21" },
        { label: "NEPRA Consumer Service Manual 2021", url: "https://nepra.org.pk/", retrievedOn: "2026-03-21" },
        { label: "Punjab Provincial Electricity Inspectorate", url: "https://energy.punjab.gov.pk/", retrievedOn: "2026-03-21" },
      ],
      lastReviewed: "2026-03-21",
      author: "CheckBillsOnline Editorial",
    },

    "new-connection": {
      metaTitle: "MEPCO New Connection â€” Apply Online, Documents, Deposit, Timeline",
      metaDescription:
        "How to apply for a new MEPCO electricity connection. Document checklist, security deposit slabs, site-visit timeline, demand notice and energisation steps, plus net-metering and change-of-name.",
      h1: "MEPCO new connection â€” the full application process",
      intro:
        "MEPCO accepts new-connection applications online via mepco.com.pk â†’ New Connection, or in person at any subdivision office. The end-to-end process â€” application submission to meter energisation â€” typically takes 30 working days for residential single-phase under 5 kW, and longer for three-phase, high-load, or net-metered connections that need transformer or service-line work.",
      sections: [
        { id: "documents", heading: "Document checklist for residential new connection",
          paragraphs: [
            "Ownership proof â€” sale deed, allotment letter, or rental agreement with NOC from owner. CNIC (front and back, original to be shown at site visit). Photo of the proposed meter location (the wall and the inside switchboard area). Two passport-sized photographs.",
            "For rental connections, additionally: rental agreement notarised on Rs 100 stamp paper, NOC from the property owner, and the owner's CNIC copy. Some subdivisions also ask for the owner's mobile number for verification.",
            "All documents are uploaded as scanned PDFs (under 2 MB each) on the online application or accepted in physical photocopies at the subdivision office. The application fee is currently Rs 20 (pay at the subdivision or via online card).",
          ] },
        { id: "site-visit", heading: "Site visit and demand notice",
          paragraphs: [
            "Within 5 working days of submitting the application and application fee, a MEPCO line superintendent visits the premise to verify the wiring, the proposed meter location, the requested sanctioned load, and the distance from the nearest service line.",
            "After the site visit, MEPCO issues a Demand Notice listing the security deposit, any service-line extension cost (if the nearest pole is too far), and the meter rent. The Demand Notice is valid for 60 days; pay within this window or the application lapses.",
            "Security deposit slabs (current): single-phase under 5 kW â€” Rs 500-2,500 depending on sanctioned load. Three-phase under 25 kW â€” Rs 5,000-15,000. The deposit is refundable on permanent disconnection and accrues interest at the rate notified by NEPRA each year. For an account opened in 2025 with a Rs 2,500 deposit, that's roughly Rs 200/year accrued interest.",
          ] },
        { id: "energisation", heading: "Meter installation and energisation",
          paragraphs: [
            "After Demand Notice payment, MEPCO schedules the meter installation. For residential single-phase under 5 kW, this typically happens within 7-21 days. For three-phase or high-load connections that need a new transformer or extended service line, the timeline can extend to 60-90 days because the upstream-network work involves grid-substation approvals.",
            "The meter is installed by a MEPCO line crew. You should be present (or have an adult representative) to receive the meter, verify the seal numbers, and photograph the initial reading. The crew issues a temporary commissioning slip; the formal connection certificate is mailed within a week.",
            "MEPCO must commit to the NEPRA SoP-prescribed timeline; if MEPCO misses it without valid technical reason, you are entitled to compensation per the Standards of Performance â€” file via the SDO. Common reasons for delay: pending demand-notice payment, missing documents, neighbour disputes over service-line right-of-way.",
          ] },
        { id: "name-change", heading: "Change of Name (CON) on an existing connection",
          paragraphs: [
            "If you have just bought a property or inherited a connection, file a Change of Name rather than a new connection. The CON fee is Rs 200, the deposit transfers from the previous owner, and the timeline is 15 working days.",
            "Documents: sale deed or transfer letter, both buyer's and seller's CNICs, the previous month's paid bill (must be clear of arrears), and the CON application form. The application is filed at the subdivision; some subdivisions also accept online uploads via mepco.com.pk.",
            "Tip: pay any outstanding arrears before filing CON. Otherwise the application is parked until the meter master is clean. Some subdivisions will let you pay the arrears as part of the CON filing and process both together.",
          ] },
        { id: "net-metering", heading: "Net-metering for rooftop solar",
          paragraphs: [
            "If you intend to install rooftop solar, the new-connection form on mepco.com.pk has a separate Net Metering section. AEDB (Alternative Energy Development Board) registration of your installer is mandatory in Pakistan; MEPCO will not accept a net-metering application from a non-AEDB installer.",
            "End-to-end timeline is 60-90 days: 5 days for site survey, 30-45 days for installation by your contractor, 7-15 days for MEPCO's witness test (a MEPCO engineer verifies the inverter synchronisation and seals the bi-directional meter), and 7-10 days for the agreement signing and grid commissioning.",
            "Residential systems up to 25 kW are eligible. Most rooftop systems for households are 3-10 kW. The federal solar subsidy (current) applies to systems under 5 kW and covers approximately 30% of capital cost. Check with your AEDB installer for the current subsidy paperwork.",
            "Two warnings. First, ensure your CSS registration (if applicable) accounts for net consumption â€” net-metered homes with sanctioned load above 1 kW may not qualify for the protected slab even if net units are below 200. Second, the inverter must be on the AEDB-approved list; non-listed inverters fail the witness test and the system is not commissioned.",
          ] },
      ],
      faq: [
        { q: "How much is the MEPCO security deposit?", a: "Residential single-phase under 5 kW: Rs 500-2,500 by NEPRA slab. Higher load brackets have higher deposits. Refundable on permanent disconnection." },
        { q: "Can I apply for a new connection as a tenant?", a: "Yes â€” with a rental agreement notarised on Rs 100 stamp paper, NOC from the owner, and the owner's CNIC. The connection is in the tenant's name." },
        { q: "What is the timeline for a new MEPCO connection?", a: "30 working days for residential single-phase under 5 kW. 60-90 days for three-phase, high-load, or connections that need transformer or extended service-line work." },
        { q: "How much does net-metering cost?", a: "A 3 kW residential system costs approximately Rs 4-5 lakh after federal subsidy. Payback is in 4-6 years assuming a 600-unit-per-month household. AEDB-registered installer paperwork is mandatory." },
      ],
      citations: [
        { label: "MEPCO New Connection page", url: "https://www.mepco.com.pk/", retrievedOn: "2026-04-30" },
        { label: "NEPRA SoP Regulations â€” New Connection timelines", url: "https://nepra.org.pk/", retrievedOn: "2026-04-30" },
        { label: "AEDB Net Metering Regulations", url: "https://www.aedb.org/", retrievedOn: "2026-04-30" },
      ],
      lastReviewed: "2026-04-30",
      author: "CheckBillsOnline Editorial",
    },

    faq: {
      metaTitle: "MEPCO FAQ â€” Most-Asked Questions About MEPCO Bills, Tariff, and Service",
      metaDescription:
        "All the common questions about MEPCO bills, reference numbers, tariff slabs, payments, complaints, load shedding, smart meters, and new connections â€” answered with citations to NEPRA and PITC.",
      h1: "MEPCO â€” frequently asked questions",
      intro:
        "These are the questions our editors hear most often about MEPCO. Every answer cites a primary source where applicable â€” NEPRA tariff orders, PITC consumer master, MEPCO official site, and the Electricity Act 1910 as amended.",
      sections: [],
      faq: [
        { q: "What is the MEPCO reference number?", a: "A 14-digit identifier printed at the top-right of every bill. The only number you need to view, download, or pay your bill online." },
        { q: "How do I check my MEPCO bill online?", a: "Enter the 14-digit reference into the form at the top of this page. We fetch the bill in real time from PITC and display it in a sandboxed iframe. No login, no fee." },
        { q: "Is there an official MEPCO app?", a: "Yes â€” \"MEPCO Multan Electric Power Company\" on Google Play. No official iOS app yet; iPhone users should bookmark this page or bill.pitc.com.pk/mepcobill." },
        { q: "What is the MEPCO customer-care number?", a: "Universal DISCO helpline 118 (toll-free, 24x7). For escalations: gm.cs@mepco.com.pk." },
        { q: "Why is my MEPCO bill higher than last month?", a: "Slab transition (crossing 200 or 700 units), FPA spike (Fuel Price Adjustment notified by NEPRA monthly), or meter-reader error. See the hub page for the full diagnostic." },
        { q: "How long does payment take to reflect?", a: "JazzCash, Easypaisa, NayaPay, SadaPay, and bank-app payments via 1Link: instant. Cash at MEPCO counters or authorised bank branches: 4 working hours. Cheques: 2-3 working days." },
        { q: "What if my MEPCO bill is wrong?", a: "Visit your local SDO with the bill. The SDO can correct meter-reader errors and issue a fresh bill within 7 working days. Escalate to GM CS after 15 days." },
        { q: "How do I switch to the protected tariff?", a: "Register on the Cross Subsidy Program at css.pitc.com.pk. Eligibility requires a six-month rolling average at or below 200 units/month and one live connection per CNIC. See our CSS guide." },
        { q: "Can I pay my MEPCO bill from outside Pakistan?", a: "Yes â€” through your Pakistani bank's mobile app. JazzCash and Easypaisa require a Pakistani SIM for OTP." },
        { q: "What is the MEPCO late-payment penalty?", a: "10% of the energy-charge portion if paid between due date and disconnection date. After disconnection, a reconnection fee of Rs 200-1,000 is added." },
        { q: "How do I apply for a new MEPCO connection?", a: "Online via mepco.com.pk â†’ New Connection or at any subdivision office. See the new-connection spoke for the full document checklist and timeline." },
        { q: "Why is my consumer name wrong on the bill?", a: "Apply for Change of Name (CON) at your local subdivision. Documents: sale deed, both CNICs, last paid bill (no arrears), Rs 200 fee. Takes 15 working days." },
        { q: "Is MEPCO available outside southern Punjab?", a: "No. MEPCO covers only 13 districts of southern Punjab. Other DISCOs cover the rest of Pakistan: LESCO (Lahore/Kasur/Okara/Sheikhupura), IESCO (Islamabad/Rawalpindi), FESCO (Faisalabad), GEPCO (Gujranwala/Sialkot), PESCO (Peshawar), HESCO (Hyderabad), SEPCO (Sukkur), QESCO (Quetta/Balochistan), TESCO (tribal districts), HAZECO (Hazara), and K-Electric (Karachi)." },
        { q: "Does MEPCO offer net-metering?", a: "Yes. Residential systems up to 25 kW. AEDB-registered installer required. Timeline 60-90 days end-to-end." },
        { q: "Are MEPCO bills accepted as proof of address?", a: "Yes. The PDF downloaded from this page carries the PITC verification stamp and is accepted by all Pakistani banks, NADRA, the passport office, and consular departments â€” provided the bill is dated within the last 3 months and the name on the bill matches the applicant." },
      ],
      citations: [
        { label: "MEPCO Help & FAQ", url: "https://www.mepco.com.pk/", retrievedOn: "2026-05-09" },
        { label: "NEPRA Consumer Service Manual 2021", url: "https://nepra.org.pk/", retrievedOn: "2026-03-21" },
      ],
      lastReviewed: "2026-05-09",
      author: "CheckBillsOnline Editorial",
    },
  },
};

MEPCO.spokes.tariff.tariff = MEPCO.hub.tariff;

